services:
  watchyourlan:
    image: aceberg/watchyourlan:2.1.4
    volumes:
      - ./data:/data/WatchYourLAN
    environment:
      - IFACES=wlan0
      - HOST=0.0.0.0
      - PORT=8840
      - TZ=Asia/Shanghai
      - USE_DB=sqlite # postgres
      # PG_CONNECT=postgres://username:password@postgres:5432/dbname?sslmode=disable
    network_mode: host
    restart: unless-stopped
