version: "3.8"

services:

  optaweb:
    image: vimagick/optaweb-employee-rostering
    ports:
      - "8080:8080"
#   environment:
#     - POSTGRES_DB=optaweb
#     - POSTGRES_USER=optaweb
#     - POSTGRES_PASSWORD=optaweb
#   depends_on:
#     - postgres
    restart: unless-stopped

# postgres:
#   image: postgres:14-alpine
#   volumes:
#     - ./data:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_DB=optaweb
#     - POSTGRES_USER=optaweb
#     - POSTGRES_PASSWORD=optaweb
#   restart: unless-stopped
