version: "3.8"
services:
  openrefine:
    image: vimagick/openrefine
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data
    environment:
      - REFINE_INTERFACE=0.0.0.0
      - REFINE_PORT=3333
      - REFINE_MIN_MEMORY=1024M
      - REFINE_MEMORY=1024M
      - REFINE_DATA_DIR=/data
    restart: unless-stopped
