scrapyd:
  image: vimagick/scrapyd
  ports:
    - "6800:6800"
  volumes:
    - ./data:/var/lib/scrapyd
    - /usr/local/lib/python2.7/dist-packages
  restart: unless-stopped

scrapy:
  image: vimagick/scrapyd
  command: bash
  volumes:
    - .:/code
  working_dir: /code
  restart: unless-stopped

scrapyrt:
  image: vimagick/scrapyd
  command: scrapyrt -i 0.0.0.0 -p 9080
  ports:
    - "9080:9080"
  volumes:
    - .:/code
  working_dir: /code
  restart: unless-stopped
