version: "3.8"

services:

  recorder:
    image: vimagick/ot-recorder
    ports:
      - "8083:8083"
      - "8085:8085"
    volumes:
      - ./data:/var/spool/owntracks/recorder/store
    environment:
      - OTR_HOST=mqtt.eclipse.org
      - OTR_PORT=8883
      - OTR_USER=username
      - OTR_PASS=password
      - OTR_TOPICS=owntracks/#
      - OTR_CAPATH=/etc/ssl/certs/
      # OTR_OPTIONS=--debug
    restart: unless-stopped

  frontend:
    image: owntracks/frontend
    ports:
      - "8080:80"
    environment:
      - LISTEN_PORT=80
      - SERVER_HOST=recorder
      - SERVER_PORT=8083
    restart: unless-stopped
