version: "3.8"

services:

  nodebb:
    image: vimagick/nodebb
    ports:
      - "4567:4567"
    volumes:
      - ./data:/var/lib/nodebb
      - /usr/src/nodebb/build
      - /usr/src/nodebb/node_modules
      - /usr/src/nodebb/public/uploads
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - ./data:/data
    restart: unless-stopped
