version: "3.8"
services:
  v4l2rtspserver:
    image: mpromonet/v4l2rtspserver:latest-arm32v7
    command: -v -P554 -H640 -W480 -F5 -ulive
    ports:
      - "554:554"
    devices:
      - /dev/video0
    restart: unless-stopped
