graphite:
  image: vimagick/graphite
  ports:
    - "2003:2003"
    - "2003:2003/udp"
    - "2004:2004"
    - "7002:7002"
    - "8080:8080"
    - "9001:9001"
  volumes:
    - ./data/conf:/opt/graphite/conf
    - ./data/storage:/opt/graphite/storage
  restart: always
