version: "3.8"
services:
  owncast:
    image: easypi/owncast-arm
    command: /app/owncast -backupdir=/data -database=/data/database.db
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
