odoo:
  image: odoo:12
  ports:
    - "8069:8069"
  volumes:
    - ./data/odoo:/var/lib/odoo
    - ./data/addons:/mnt/extra-addons
  links:
    - postgres:db
  restart: always

postgres:
  image: postgres:9-alpine
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
  restart: always
