opencart:
  image: opencart
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - /var/www/html
  restart: always

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=opencart
  restart: always

