version: "3.8"

services:

  semaphore:
    image: ansiblesemaphore/semaphore:v2.8.77
    ports:
      - "3000:3000"
    volumes:
      - ./data/semaphore:/etc/semaphore
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB: semaphore?sslmode=disable
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphore
      POSTGRES_DB: semaphore
    restart: unless-stopped
